// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// 
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC4rov3f2I7d-nkCpc1kkvnCzWGYT-bQk',
    appId: '1:1047140106623:web:467390811b36d1166f5a4a',
    messagingSenderId: '1047140106623',
    projectId: 'loginklone',
    authDomain: 'loginklone.firebaseapp.com',
    storageBucket: 'loginklone.appspot.com',
    measurementId: 'G-P9SKZV4F9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEA0Qwuv8ol4_bem6DkeMmKAcGVuVk9Co',
    appId: '1:1047140106623:android:3ad20b3e43a5c95d6f5a4a',
    messagingSenderId: '1047140106623',
    projectId: 'loginklone',
    storageBucket: 'loginklone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPGajiTCi2f976AReaKbtyrMkio2ADFDI',
    appId: '1:1047140106623:ios:c0699b5915893be26f5a4a',
    messagingSenderId: '1047140106623',
    projectId: 'loginklone',
    storageBucket: 'loginklone.appspot.com',
    iosClientId: '1047140106623-asecdk8qp5c2775as0p1ac4gp6iim0c4.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginScreenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPGajiTCi2f976AReaKbtyrMkio2ADFDI',
    appId: '1:1047140106623:ios:c0699b5915893be26f5a4a',
    messagingSenderId: '1047140106623',
    projectId: 'loginklone',
    storageBucket: 'loginklone.appspot.com',
    iosClientId: '1047140106623-asecdk8qp5c2775as0p1ac4gp6iim0c4.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginScreenApp',
  );
}
